---
clusterName: k8s

endpoint: "https://k8s.srbgod.io:6443"


talosVersion: v1.5.4
kubernetesVersion: 1.28.3

additionalApiServerCertSans:
  - 10.0.1.10

additionalMachineCertSans:
  - 10.0.1.10
  - k8s.srbgod.io

cniConfig:
  name: none

nodes:
  # S1 10600k / 128GB / 4x4TB SSD / 10GbE / 2x1TB NVME / 2x500GB SSD
  - hostname: s1.srbgod.io
    ipAddress: 10.0.1.211
    installDiskSelector:
      busPath: /pci0000:00/0000:00:01.0/0000:01:00.0/0000:02:08.0/0000:03:00.0/ata5/host4/target4:0:0/4:0:0:0/
    controlPlane: true
    disableSearchDomain: true
    nameservers:
      - 1.1.1.1
    networkInterfaces:
      - interface: eno1
        mtu: 1500
        dhcp: true

  
  # macm 2018 3.2GHz / 32GB / 256GB SSD / 10GbE
  - hostname: s2.srbgod.io
    ipAddress: 10.0.1.133
    installDiskSelector:
      busPath: /pci0000:00/0000:00:17.0/ata7/host6/target6:0:0/6:0:0:0/
    controlPlane: true
    disableSearchDomain: true
    nameservers:
      - 1.1.1.1
    networkInterfaces:
      - interface: enp6s0
        mtu: 1500
        dhcp: false

controlPlane:
  patches:
    - |-
      machine:
        features:
          kubernetesTalosAPIAccess:
            enabled: true
            allowedRoles:
              - os:admin
            allowedKubernetesNamespaces:
              - kube-system
  inlinePatch:
    cluster:
      allowSchedulingOnMasters: true
      proxy:
        disabled: true
      etcd:
        extraArgs:
          listen-metrics-urls: http://0.0.0.0:2381
        advertisedSubnets:
          - 10.0.1.0/24
      controllerManager:
        extraArgs:
          bind-address: 0.0.0.0
      scheduler:
        extraArgs:
          bind-address: 0.0.0.0
      discovery:
        registries:
          service:
            disabled: true
    machine:
      install:
        extensions:
          - image: ghcr.io/siderolabs/i915-ucode:20230919
          - image: ghcr.io/siderolabs/intel-ucode:20230808
      features:
        kubePrism:
          enabled: true
          port: 7445
      network:
        extraHostEntries:
          - ip: 10.0.1.10
            aliases:
              - k8s.srbgod.io
      time:
        disabled: false
        servers:
          - time.cloudflare.com
      kubelet:
        extraArgs:
          feature-gates: GracefulNodeShutdown=true
          rotate-server-certificates: true
        nodeIP:
          validSubnets:
            - 10.0.1.0/24
      files:
        - content: |
            [plugins."io.containerd.grpc.v1.cri"]
              enable_unprivileged_ports = true
              enable_unprivileged_icmp = true
          path: /etc/cri/conf.d/20-customization.part
          op: create